Document: mypackage
Title: Debian mypackage Manual
Author: <insert document author here>
Abstract: This manual describes what mypackage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mypackage/mypackage.sgml.gz

Format: postscript
Files: /usr/share/doc/mypackage/mypackage.ps.gz

Format: text
Files: /usr/share/doc/mypackage/mypackage.text.gz

Format: HTML
Index: /usr/share/doc/mypackage/html/index.html
Files: /usr/share/doc/mypackage/html/*.html
